# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eftrecord',
            name='etf_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
